version: '3.3'
services:
  tasks:
    build: './'
    volumes:
      - './:/app:delegated'
      - 'tmp:/mnt/tmp'
    ports:
      - '9229:9229'
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
volumes:
  tmp:
